### ISSUE TITLE
Add data loading example/instructions to website

### ISSUE THREAD

**Issue by chrisprice** [ScottLogic/d3fc#438]
I had some feedback that someone had to find an example from another library to show them how to load real data. Having reviewed the website, all of the examples on the website render either static or random data. I think with the changes to the data package, we could at least add an example to the website or instructions to the package README.

**Comment by ColinEberhardt** [comment]
Good idea. Rather than just adding documentation, why not add a Yahoo data loader? Something that takes Yahoo CSV and parses it into the 'default' format supported by our series / indicators.

Funnily enough, I already have one of these.

For an initial implementation I wouldn't make it fully featured (Yahoo supports a lot of different configuration options).

**Comment by chrisprice** [comment]
I'd be interested in seeing a bitcoin provided as well, [Coinbase](https://docs.exchange.coinbase.com/#get-historic-rates) looks like a good candidate.

**Comment by bjedrzejewski** [comment]
@jdunkerley With the coinbase and quandl we can close it now maybe?
