### ISSUE TITLE
IE9 error

### ISSUE THREAD

**Issue by chrisprice** [ScottLogic/d3fc#458]
When viewing a number of the website examples, the following error is thrown and the chart doesn't or partially renders -

`SCRIPT438: Object doesn't support property or method 'querySelectorAll' 
scripts.js, line 564 character 5`

**Comment by ColinEberhardt** [comment]
I had a quick looks this morning before heading off to the train, it looks like this error is being thrown in the line annotation example. The error is due to D3 invoking `querySelectorAll` on an object that is not a DOM element as expected:

https://github.com/mbostock/d3/blob/78e0a4bb81a6565bf61e3ef1b898ef8377478766/d3.js#L564

This might be due to the code we have in `dataJoin` that ensures the container is a `d3.selection`.

That's as far as I got this morning, I don't have access to IE now ;-)

**Comment by chrisprice** [comment]
I'll take a quick look

**Comment by chrisprice** [comment]
Confirmed https://github.com/mbostock/d3/issues/851
