### ISSUE TITLE
IDEA: Create our own axis implementation

### ISSUE THREAD

**Issue by ColinEberhardt** [ScottLogic/d3fc#466]
One thing that I find a little frustrating with the D3 axes is that there isn't an elegant way to re-position the labels. The [standard solution](http://stackoverflow.com/questions/17544546/d3-js-align-text-labels-between-ticks-on-the-axis) seems to be to render the axis then tweak the results. 

For example:

```
d3.selectAll('.x-axis text')
    .style('text-anchor', 'left')
    .attr('transform', 'translate(35, 0)');
```

Which is pretty ugly.

If the axis were re-implemented / wrapped / adapted to follow the decorate pattern, the above code could be implemented as part of the enter selection via decorate.

Thoughts?

**Comment by chrisprice** [comment]
Interesting. So the new code would look like -

```js
  fc.svg.axis()
    .decorate(function(g) {
      g.enter()
        .selectAll('text')
        .style('text-anchor', 'left')
        .attr('transform', 'translate(35, 0)');
    });
```

Although the code above would fail because the axis can subsequently create elements...

How would we avoid the additional container element? *E.g. I want the axis to render into a g, but due to the data join, our implementation renders a containing g into that which then contains the axis.*

I'm a bit concerned that we'd end up re-implementing the axis...
