### ISSUE TITLE
Re-rendering bollinger bands causes duplicates

### ISSUE THREAD

**Issue by djmiley** [ScottLogic/d3fc#493]
When zooming or resizing http://scottlogic.github.io/d3fc/ without reloading the page, bollinger bands are constantly drawn but previous ones are still visible. 
![d3fcbollingerbands](https://cloud.githubusercontent.com/assets/13115186/8677333/560e81d6-2a46-11e5-90f6-89b15725729b.jpg)

**Comment by chrisprice** [comment]
Thanks @djmiley, nice find! 

I know you're trying to learn your way around the library, so if you fancy trying to fix it: the bug was caused by [this change](https://github.com/ScottLogic/d3fc/commit/267057f2f99678b9ace429e9b0103c9917c440b3) and you'll need to change this line to [fix it](https://github.com/ScottLogic/d3fc/blob/master/src/indicator/renderer/bollingerBands.js#L44). No worries if you don't.
