### ISSUE TITLE
Multi Series Sequences Colour Sequences On Each New Series

### ISSUE THREAD

**Issue by jdunkerley** [ScottLogic/d3fc#629]
Would be nice if each line was a different colour by default within a multi series object.

Think could be done by adding a class to the container. Ideally guess would skip things that aren't series (e.g. gridlines) but that is a minor detail.

**Comment by chrisprice** [comment]
Hmm not sure, I can't see how to do this in a generic way and it's pretty easy to do manually with `decorate` e.g. 

```js
multi()
  .decorate((g) => g.attr('class', (d, i) => `series-${i}`))
```

Have you got an idea for how to do it generically or an example of where the above wouldn't work?

**Comment by jdunkerley** [comment]
Have been trying to find a good way to do generally. 

I thought if we added a common class to the enclosing g on the various series it would be quite straight forward (I think all except area and lines are contained in a g already). This could then have the stroke and fill colours on it and be picked up automatically. Hoped could be used in the stacked implementation as well.

**Comment by chrisprice** [comment]
Sorry, I think I'm still missing what you're trying to achieve?

Once upon a time `line` and `area` did actually have containers. However, I've been on a one-man crusade to eliminate as many of them as we can because I think superfluous `g`s in the SVG DOM make it harder to understand, navigate and style.

**Comment by jdunkerley** [comment]
was aiming a way so that colours could be defined in a single place something like:
```css

.series {
  stroke: #06c;
  fill: #9cf;
}

g.multi.item2 .series {
  stroke: #c60;
  fill: #c96;
}
```

The multi series can then just append the item# in rotation.

We wouldn't need an extra g as could just add the series class to each of the drawn elements

**Comment by jdunkerley** [comment]
Submitted a WIP PR #632 showing what I was thinking off.

**Comment by ColinEberhardt** [comment]
I'd say it is easy-ish to add classes with decorate, however it is a little more complex with grouped / stacked where you need to use the index for the series being decorated rather than the index of the datum:

https://github.com/ScottLogic/d3fc/blob/master/visual-tests/series/grouped-bar.js#L31

I'd be happy to see a simpler solution to this as long as it is elegant, and also solves the problem for stacked / grouped also.

**Comment by chrisprice** [comment]
Most stylistic attributes in SVG are inherited so you can just target the mutli classes e.g. -
```js
g.multi.item2 {
  stroke: #c60;
  fill: #c96;
}
```

Excluding the edge case @ColinEberhardt mentioned, I still think this is better done as a decorate method e.g. -

```js
const colors = d3.scale.category10();

multi()
  .decorate((g) => g.style({fill: (d, i) => category10(i), stroke: (d, i) => category10(i)}))
```

**Comment by jdunkerley** [comment]
my thought on having a series class was to avoid the current split

```css
path.line {
  fill: none;
  stroke: #06c;
}

path.area {
  fill: #9cf;
}

.point>circle {
  stroke: #06c;
  fill: #9cf;
}

.bar>path {
  stroke: #06c;
  fill: #9cf;
}
```

and unify into a single entry for colour control. As we currently have it set on a very specific level didn't want to change it to affect all child elements.

**Comment by chrisprice** [comment]
Ah, I think I get it now! Could we use inheritance of `fill`/`stroke` inline styles set by a `decorate` using a `d3.scale.category10` combined with default css which uses `fill-opacity`/`stroke-opacity` to appropriately hide/half-show/show the colours?

So maybe by default everything renders in greyscale (apart from `ohlc`/`candlestick`?) and the only css we have is for fading the stroke or fill?

I've knocked up a quick [JS Bin](http://jsbin.com/nifecayapu/edit?html,css,output) which shows the how the colours are inherited.

**Comment by jdunkerley** [comment]
definitely could work for the multi method, will finish off my go with the css class and then take a look at doing it that way

**Comment by ColinEberhardt** [comment]
Another thing worth considering is the `nth-child` CSS selector, which gives more flexibility that classes such as `item2`, for example, this will style the second multi-series:

```
g.multi:nth-child(2) path {
    stroke: red;
}
```

It also works with stacked series:

```
g.stacked:nth-child(2) path {
    fill: red;
}
```

I have a feeling that in the past we used decorate due to CSS specificity / inheritance issues, although I cannot remember the specifics.

**Comment by jdunkerley** [comment]
I did some more playing with having a series class, one thing that came up when I was working with the visual tests is wanting the ability to control the index for different series. Added a seriesIndex property allowing you to control this. 

While I like the nth-child idea, think the ability to control the 'index' makes it easy to achieve nice results. Not sure how we could do that with the child index. 

Have updated the #632 PR, would appreciate comments. Still need to have a look at how to integrate with stacked/grouped.

**Comment by chrisprice** [comment]
This comes across as a pretty specific use-case, which we've previously
dealt with using decorate rather than add more to the API.

I do prefer the idea of a CSS files which would set some default colours
for stacked/multi using nth-of-type (or equivalent).

I'd also like to see the rest of the component CSS moved inline to
control fill/stroke
opacity and overflow appropriately to produce appropriate greyscale
renderings (maybe as a default decorate?).

When both of the above are included you're left with a decent colourful
rendering which you can either theme by specifying custom CSS, or decorate
to your hearts content.

**Comment by jdunkerley** [comment]
Will have a go at using the nth of type and see how that works out

**Comment by jdunkerley** [comment]
Have created another WIP PR #640 with the styles done via multi class with an nth-of-type property. Less changes needed for this method, I think. Not sure the best way to set the default stroke and fill to affect only the right things on this method.

Also updated the original PR so both are running all of the visual tests completely. 

Going to look at the stacked and grouped charts next and see how can integrate into those.

**Comment by ColinEberhardt** [comment]
I'm much more in support of the `nth-child` approach, it is consistent with the way we are currently using CSS.

I'll just add a `.gitignore` rule on @chrisprice computer for `*.css` ;-)

**Comment by jdunkerley** [comment]
Ok will close the other PR and work on integrating stacked and grouped within the #640 one

**Comment by jdunkerley** [comment]
Added in `.stacked:nth-child` entries to the series.css.

The stacked example is not automatically coloured without a decorate function (admittedly in pastel fills but hey):

![image](https://cloud.githubusercontent.com/assets/4699705/10639192/c8fe245e-7806-11e5-8289-7714e9f03d4c.png)

Think this is a good solution. Only thing don't love is changing the style of svg and text globally (hence my suggestion of adding a `series` class to everything).

**Comment by chrisprice** [comment]
Ohh pretty, where are you getting the colours from BTW? Are they from d3.series.category10?

**Comment by jdunkerley** [comment]
Colour sequence came from rotating the hue of the default blue through 30 degrees.
