### ISSUE TITLE
Theme support for d3fc

### ISSUE THREAD

**Issue by bjedrzejewski** [ScottLogic/d3fc#665]
Once the CSS files are under control and the automatic coloring is there- why not give a theme support for d3fc? It could be interesting to have all d3fc charts change their default appearance based on a single CSS file that could be amended either by us providing some default theme options or by the users to match their websites / products?

**Comment by ColinEberhardt** [comment]
I'm really not too keen on this for a few different reasons:

  1. We keep our CSS very 'slim' which should make it easy for someone to theme the chart.
  2. Creating themes would be another 'fragile' thing to maintain. It is not readily testable.
  3. Everyone else does it!

For me (3) is the most significant one. The whole reason we are doing d3fc is because we believe we have something different to offer, a unique perspective. As a result, we have been careful not to veer off into rolling our the usual patterns and solutions.

**Comment by bjedrzejewski** [comment]
I used a lot of http://www.primefaces.org/ in the past so, they do themes great and thats why I may be a bit biased.

I agree with the point 2 and 3. For 1 though- isn't it easier to style a chart if we would never to use incline colors / css and fully rely on good named classes in CSS? Could this be a good compromise?
