### ISSUE TITLE
Add error bar series

### ISSUE THREAD

**Issue by bjedrzejewski** [ScottLogic/d3fc#700]
As described in the vision for d3fc, error bar series would be useful.  We can draw then in couple ways, so feedback is welcome. Here are examples:

https://en.wikipedia.org/wiki/Error_bar
http://scienceblogs.com/cognitivedaily/2008/07/31/most-researchers-dont-understa-1/

Or should we go as far as to make these:

https://en.wikipedia.org/wiki/Box_plot

**Comment by ColinEberhardt** [comment]
This feels like a few different things to me, an error bar series that renders the following:

```
-----
  |
  |
  |
  |
  |
-----
```

This can then be combined with a point series, or a bar series depending on the needs. It should also support an orient property so that you can render error bars in x or y, or both (by combining two series with multi).

The box plot looks like a dedicated series type to me.

**Comment by bjedrzejewski** [comment]
Lets make this issue about error bars then and another one for box plots if you think they are useful.

**Comment by bjedrzejewski** [comment]
@ColinEberhardt I was originally planning to make a single series than can render horizontal and vertical. Do you think that orient property and multi is a far superior choice?

**Comment by ColinEberhardt** [comment]
No, that sounds spot on, a relatively simple series that can render horizontal or vertical error bars. It is then up to the user to combine that series (via multi) with various other series. Or, they could combine both horizontal and vertical error bars into a single series.

Our main aim here is to give people the building blocks rather than the complete (and most often constrained) solution.
