### ISSUE TITLE
Ticks labels on the edge are cropped

### ISSUE THREAD

**Issue by zeleniy** [ScottLogic/d3fc#819]
See this example http://scottlogic.github.io/d3fc/examples/simple/
On y axis most top label (1.2) is cropped. Is there any quick way to fix this problem?

**Comment by ColinEberhardt** [comment]
Hi, yes, this is quite easy to do via the `margin` property. Taking the example code you can add a top and right margin as follows:

    margin({top: 20, left: 50, bottom: 20, right: 20})

You can see a complete example here where I have styled the parent SVG giving it a border so that you can see the margin more clearly:

http://jsbin.com/fevofuvehi/1/edit?html,css,js,output

**Comment by zeleniy** [comment]
It works! Thank you very much!
